[functions]
  node_bundler = "esbuild"   # modern bundler, smaller zip

[[redirects]]
  from = "/api/chat"
  to   = "/.netlify/functions/chat"
  status = 200

[build.environment]
  NODE_VERSION = "20"